common/models/Customers.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "customers".
 *
 * @property int $id
 * @property int $rc
 * @property int $category
 * @property string $name
 * @property string $last_name
 * @property string $type_doc
 * @property int $num_doc
 * @property string $addres
 * @property string $phone
 * @property string|null $email
 * @property string $eps
 * @property string $afp
 * @property string $arl
 * @property string $ccf
 * @property int $association
 * @property string|null $office
 * @property string $user
 * @property string $key_system
 * @property string $date_register
 *
 * @property Categories $category0
 * @property Associations $association0
 * @property Payments[] $payments 
 */
class Customers extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'customers';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['rc', 'category', 'name', 'last_name', 'type_doc', 'num_doc', 'addres', 'phone', 'eps', 'afp', 'arl', 'ccf', 'association', 'user', 'key_system', 'date_register'], 'required'],
            [['rc', 'category', 'num_doc', 'association'], 'integer'],
            [['date_register'], 'safe'],
            [['name', 'last_name', 'addres', 'phone', 'office', 'user', 'key_system'], 'string', 'max' => 100],
            [['type_doc', 'email', 'eps', 'afp', 'arl', 'ccf'], 'string', 'max' => 50],
            [['category'], 'exist', 'skipOnError' => true, 'targetClass' => Categories::class, 'targetAttribute' => ['category' => 'id']],
            [['association'], 'exist', 'skipOnError' => true, 'targetClass' => Associations::class, 'targetAttribute' => ['association' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'rc' => 'Rc',
            'category' => 'Categoría',
            'name' => 'Nombres',
            'last_name' => 'Apellidos',
            'type_doc' => 'Tipo Doc',
            'num_doc' => 'Num Documento',
            'addres' => 'Dirección',
            'phone' => 'Teléfono',
            'email' => 'E-mail',
            'eps' => 'Eps',
            'afp' => 'Afp',
            'arl' => 'Arl',
            'ccf' => 'Ccf',
            'association' => 'Gremio',
            'office' => 'Cargo',
            'user' => 'Usuario',
            'key_system' => 'Contraseña',
            'date_register' => 'Fecha de Registro',
        ];
    }

    /**
     * Gets query for [[Category0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCategory0()
    {
        return $this->hasOne(Categories::class, ['id' => 'category']);
    }

    /** 
     * Gets query for [[Association0]]. 
     * 
     * @return \yii\db\ActiveQuery 
     */
    public function getAssociation0()
    {
        return $this->hasOne(Associations::class, ['id' => 'association']);
    }

    /**
     * Gets query for [[Payments]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getPayments()
    {
        return $this->hasMany(Payments::class, ['customer_id' => 'id']);
    }
}

backend/controllers/CustomersController.php
<?php

namespace backend\controllers;

use common\models\Customers;
use backend\models\CustomersSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CustomersController implements the CRUD actions for Customers model.
 */
class CustomersController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Customers models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new CustomersSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Customers model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Customers model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Customers();
        $model->date_register = date('Y-m-d');
        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Customers model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Customers model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Customers model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Customers the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Customers::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/controllers/PaymentsController.php
<?php

namespace backend\controllers;

use common\models\Payments;
use backend\models\PaymentsSearch;
use common\models\Categories;
use common\models\Customers;
use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PaymentsController implements the CRUD actions for Payments model.
 */
class PaymentsController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Payments models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new PaymentsSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionDetail()
    {
        $searchModel = new PaymentsSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);
        $model_customer = Customers::find()->where(['id' => Yii::$app->request->get('id')])->one();

        return $this->render('detail', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'model' => $model_customer
        ]);
    }

    /**
     * Displays a single Payments model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Payments model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Payments();
        $model->date_liquidation = date('Y-m-d');
        if ($this->request->isPost) {
            if ($model->load($this->request->post())) {
                $pension = $model->base * 0.16;  //cambiar para el 16% del valor base
                //inicio de Condicionales que asignan el valor del riesgo
                $r = 1;
                if ($model->risk_level == 1) {
                    $r = 0.00522;
                }
                if ($model->risk_level == 2) {
                    $r = 0.01044;
                }
                if ($model->risk_level == 3) {
                    $r = 0.02436;
                }
                if ($model->risk_level == 4 || $model->risk_level_2 == 4 || $model->risk_level_3 == 4) {
                    $r = 0.04350;
                }
                if ($model->risk_level == 5 || $model->risk_level_3 == 5) {
                    $r = 0.06960;
                }
                //Fin de Condicionales que asignan el valor del riesgo
                //inicio de Condicional que asigna el valor porcentual a pagar por EPS
                $cliente = Customers::find()->where(['id' => $model->customer_id])->one();
                $category = Categories::find()->where(['id' => $cliente->category])->one();
                if ($category->dependence == 1) { //dependiente
                    $percent_eps = 0.04;
                    $ccf = $model->base * 0.04;                   
                }
                if ($category->dependence == 0) { //independiente
                    $percent_eps = 0.125;
                    $ccf = $model->base * 0.02;        
                }
                //Fin de Condicional que asigna el valor porcentual a pagar por EPS
                //Inicio de Condicional que asigna el valor a pagar según factor
                if ($model->factors == 1) {
                    $model->real_value = $model->base * $percent_eps + $model->interest;
                    //$model->real_value = round($model->real_value, 3);
                    $model->paid_value = $model->real_value + $model->admin;
                }
                if ($model->factors == 2) { //Eps + R4
                    $model->real_value = $model->base * $percent_eps + ($model->base * $r) + $model->interest;
                    //$model->real_value = round($model->real_value, 3);
                    $model->paid_value = $model->real_value + $model->admin;
                }
                if ($model->factors == 3) {
                    $model->real_value = $model->base * $percent_eps + $pension + $model->interest;
                    //$model->real_value = round($model->real_value, 3);
                    $model->paid_value = $model->real_value + $model->admin;
                }
                if ($model->factors == 4) {
                    $model->real_value = ($model->base * $percent_eps) + $pension + ($model->base * $r) + $model->interest;
                    //$model->real_value = round($model->real_value, 3);
                    $model->paid_value = $model->real_value + $model->admin;
                }
                if ($model->factors == 5) {
                    $model->real_value = ($model->base * $percent_eps) + $pension + ($model->base * $r) + $ccf + $model->interest;
                    //$model->real_value = round($model->real_value, 3);
                    $model->paid_value = $model->real_value + $model->admin;
                }
                if ($model->factors == 6) {
                    $model->real_value = ($model->base * $r) + $model->interest;
                    //$model->real_value = round($model->real_value, 3);
                    $model->paid_value = $model->real_value + $model->admin;
                }
                //Fin de Condicional que asigna el valor a pagar según factor

                if ($model->save()) {
                    return $this->redirect(['view', 'id' => $model->id]);
                }
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Payments model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Payments model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Payments model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Payments the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Payments::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/customers/_form.php
<?php

use common\helpers\Core;
use yii\bootstrap4\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;

/** @var yii\web\View $this */
/** @var common\models\Customers $model */
/** @var yii\widgets\ActiveForm $form */
?>

<div class="customers-form">

    <?php $form = ActiveForm::begin(); ?>

    <div class="row">
        <div class="col-md-3">
            <?= $form->field($model, 'rc')->textInput() ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($model, 'category')->dropDownList(
                ArrayHelper::map(Core::getCategories(), 'id', 'name'),
                ['prompt' => 'Seleccione']
            ) ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($model, 'last_name')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-1">
            <?= $form->field($model, 'type_doc')->dropDownList(
                [
                    'NIT' => 'NIT',
                    'CC' => 'CC',
                    'CE' => 'CE',
                    'PT' => 'PT',
                ],
                ['prompt' => 'Seleccione']
            ) ?>
        </div>
        <div class="col-md-2">
            <?= $form->field($model, 'num_doc')->textInput() ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($model, 'addres')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($model, 'phone')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($model, 'eps')->dropDownList(
                [
                    'Compensar' => 'Compensar',
                    'Convida' => 'Convida',
                    'Ecopsos' => 'Ecopsos',
                    'Famisanar' => 'Famisanar',
                    'Fosyga Regimen de Excepción' => 'Fosyga Regimen de Excepción',
                    'Nueva EPS' => 'Nueva EPS',
                    'Salud Total' => 'Salud Total',
                    'Sanitas LTDA' => 'Sanitas LTDA',
                ],
                ['prompt' => 'Seleccione']
            ) ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($model, 'afp')->dropDownList(
                [
                    'Colfondos' => 'Colfondos',
                    'Porvenir' => 'Porvenir',
                    'Protección' => 'Protección',
                    'Skandia' => 'Skandia',                    
                    'Colpensiones' => 'Colpensiones',                    
                    'Ninguno' => 'Ninguno'
                ],
                ['prompt' => 'Seleccione']
            ) ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($model, 'arl')->dropDownList(
                [
                    'Alfa' => 'Alfa',                    
                    'Colmena' => 'Colmena',                    
                    'Colpatria' => 'Colpatria',
                    'La Equidad' => 'La Equidad',
                    'Mapfre' => 'Mapfre',                    
                    'Positiva' => 'Positiva',                    
                    'Seguros Bolivar S.A.' => 'Seguros Bolivar S.A.',
                    'Suramericana' => 'Suramericana',
                    'Ninguna' => 'Ninguna',
                ],
                ['prompt' => 'Seleccione']
            ) ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($model, 'ccf')->dropDownList(
                [
                    'Cafam' => 'Cafam',
                    'Colsubsidio' => 'Colsubsidio',                
                    'Compensar' => 'Compensar',
                    'Ninguna' => 'Ninguna',
                ],
                ['prompt' => 'Seleccione']
            ) ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'association')->dropDownList(
                ArrayHelper::map(Core::getAssociations(), 'id', 'name'),
                ['prompt' => 'Seleccione']
            ) ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'office')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'user')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'key_system')->textInput(['maxlength' => true]) ?>
        </div>
    </div>
        <div class="form-group text-center">
            <?= Html::a('Volver', ['index'], ['class' => 'btn btn-primary']) ?>
            <?= Html::submitButton('Guardar', ['class' => 'btn btn-success']) ?>
        </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/customers/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/** @var yii\web\View $this */
/** @var backend\models\CustomersSearch $model */
/** @var yii\widgets\ActiveForm $form */
?>

<div class="customers-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'rc') ?>

    <?= $form->field($model, 'category') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'last_name') ?>

    <?php // echo $form->field($model, 'type_doc') ?>

    <?php // echo $form->field($model, 'num_doc') ?>

    <?php // echo $form->field($model, 'addres') ?>

    <?php // echo $form->field($model, 'phone') ?>

    <?php // echo $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'eps') ?>

    <?php // echo $form->field($model, 'afp') ?>

    <?php // echo $form->field($model, 'arl') ?>

    <?php // echo $form->field($model, 'ccf') ?>

    <?php // echo $form->field($model, 'association') ?>
    
    <?php // echo $form->field($model, 'office') ?> 

    <?php // echo $form->field($model, 'user') ?>

    <?php // echo $form->field($model, 'key_system') ?>

    <?php // echo $form->field($model, 'date_register') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/customers/create.php
<?php

use yii\helpers\Html;

/** @var yii\web\View $this */
/** @var common\models\Customers $model */

$this->title = 'Crear Clientes';
$this->params['breadcrumbs'][] = ['label' => 'Clientes', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="customers-create">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/customers/index.php
<?php

use common\helpers\Core;
use common\models\Customers;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\ActionColumn;
use yii\grid\GridView;
use yii\helpers\ArrayHelper;

/** @var yii\web\View $this */
/** @var backend\models\CustomersSearch $searchModel */
/** @var yii\data\ActiveDataProvider $dataProvider */

$this->title = 'Clientes';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="customers-index">

    <p>
        <?= Html::a('Crear Clientes', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); 
    ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'id',
            'rc',
            'num_doc',
            'name',
            'last_name',
            [
                'attribute' => 'category',
                'value' => function ($model) {
                    return $model->category0->name;
                },
                'filter' => ArrayHelper::map(Core::getCategories(), 'id', 'name'),
            ],
            //'type_doc',
            //'addres',
            //'phone',
            //'email:email',
            'eps',
            'afp',
            'arl',
            'ccf',
            [
                'attribute' => 'association',
                //'contentOptions' => ['style' => 'vertical-align: middle;'],
                'value' => function ($model) {
                    return $model->association0->name;
                },
                'filter' => ArrayHelper::map(Core::getAssociations(), 'id', 'name'),
            ],
            //'user',
            //'key_system',
            //'date_register',
            [
                'class' => 'yii\grid\ActionColumn',
                'contentOptions' =>
                [
                    'style' => 'width: 300 px; text-align: center; vertical-align: middle; white-space: nowrap;'
                ],
                'template' => '{view} {update} {delete} ',
                'buttons' => [
                    'pagos' => function ($url, $model) {
                        return Html::a('<i class="fa fa-coins";></i>', Url::to(['/payments/detail', 'id' => $model->id]), ['title' => 'Pagos']);
                    }
                ],
            ],
        ],
    ]); ?>


</div>

backend/views/customers/update.php
<?php

use yii\helpers\Html;

/** @var yii\web\View $this */
/** @var common\models\Customers $model */

$this->title = 'Modificar Cliente: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Clientes', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
//$this->params['breadcrumbs'][] = 'Update';
?>
<div class="customers-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/customers/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/** @var yii\web\View $this */
/** @var common\models\Customers $model */

$this->title = 'Cliente: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Clientes', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="customers-view">
    <p>
        <?= Html::a('Volver', ['index'], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Modificar', ['update', 'id' => $model->id], ['class' => 'btn btn-success']) ?>
        <?= Html::a('Eliminar', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => '¿Está seguro que desea eliminar este item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'rc',
            [
                'attribute' => 'category',
                'value' => function ($model) {
                    return $model->category0->name;
                },
            ],
            'name',
            'last_name',
            'type_doc',
            'num_doc',
            'addres',
            'phone',
            'email:email',
            'eps',
            'afp',
            'arl',
            'ccf',
            [
                'attribute' => 'association',
                'value' => function ($model) {
                    return $model->association0->name;
                },
            ],
            'office',
            'user',
            'key_system',
            'date_register',
        ],
    ]) ?>

</div>